export default class Constants {
  static SHOW_DASHBOARDS_HEADER_BRIEFLY_DURATION_IN_MILLIS = 2000;

  static NOTIFICATION_DISMISS_INTERVAL_IN_MILLIS = 4000;

  static CHART_PLACEHOLDER = 'chartPlaceholder';

  static GRID_COLUMN_COUNT = 12;

  static GRID_ROW_COUNT = 12;

  static DASHBOARD_GROUP_SELECTOR_RELATIVE_HEIGHT = 0.5;

  static DASHBOARD_SELECTOR_RELATIVE_HEIGHT = 0.5;

  static SELECTOR_CONTENT_HEIGHTS_UPDATE_DELAY = 1000;

  static SLIDER_MAX_VALUE = 1000;

  static PERCENT_SLIDER_MAX_VALUE = 100;

  static DEFAULT_SLIDE_CHANGE_INTERVAL_IN_SECS = 90;

  static NBR_OF_MILLISECS_IN_SEC = 1000;

  static MAX_X_AXIS_CATEGORIES_SHOWN_COUNT = 99999;

  static MAX_FETCHED_ROWS_COUNT = 99999;

  static DEFAULT_FILL_OPACITY = 0.9;
}
